const SERVICE_NAME = 'INTL_SERVICE';

export const INTL_SERVICE_SET_LOCALE_REQUEST = `${SERVICE_NAME}_SET_LOCALE_REQUEST`;
export const INTL_SERVICE_SET_LOCALE_SUCCESS = `${SERVICE_NAME}_SET_LOCALE_SUCCESS`;
export const INTL_SERVICE_SET_LOCALE_FAILURE = `${SERVICE_NAME}_SET_LOCALE_FAILURE`;
